/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Assertions.assertEquals(2, 1 + 1);
    }
}
