/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import java.util.Scanner;
import hexlet.code.game.Even;
import hexlet.code.game.Calc;
import hexlet.code.game.Gcd;
import hexlet.code.game.Progression;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("Please enter the game number and press Enter.");
        System.out.println("1 - Greet");
        System.out.println("2 - Even");
        System.out.println("3 - Calc");
        System.out.println("4 - GCD");
        System.out.println("5 - Progression");
        System.out.println("0 - Exit");

        Scanner scanner = new Scanner(System.in);
        System.out.print("Your choice: ");
        String userChoice = scanner.next();

        switch (userChoice) {
            case "1" -> {
                Cli.greetUser();
                scanner.close();
            }
            case "2" -> {
                Even.startGame();
                scanner.close();
            }
            case "3" -> {
                Calc.startGame();
                scanner.close();
            }
            case "4" -> {
                Gcd.startGame();
                scanner.close();
            }
            case "5" -> {
                Progression.startGame();
                scanner.close();
            }
            default -> scanner.close();
        }
    }
}
